### ISSUE TITLE
Build with Xcode 7.3

### ISSUE THREAD

**Issue by ChristianVirtual** [Frugghi/iSSH2#1]
I wonder if I do something wrong ...

MacBook-Pro:iSSH2 $ pwd
/Users/cl/Documents/Development/GitHub/iSSH2
MacBook-Pro:iSSH2 $ ./iSSH2.sh 
Initializing...

Libssh2 version: 1.7.0 (Automatically detected)
OpenSSL version: 1.0.2g (Automatically detected)
SDK version: 9.3 (Automatically detected)
Architectures: armv7 armv7s arm64 i386 x86_64
OS min version: 8.0

openssl-1.0.2g.tar.gz already exists
MD5: f3c710c045cdee5fd114feb69feba7aa
Extracting openssl-1.0.2g.tar.gz
Building OpenSSL 1.0.2g, please wait...
Building libssl.a fat library...
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /var/folders/2q/v9d6rfmx6wdf6n9bhb5gqtr00000gn/T//iSSH2/openssl-1.0.2g/iPhoneOS9.3-armv7/libssl.a (No such file or directory)
Build failed, cleaning up temporary files...
MacBook-Pro:iSSH2 $ 

Any ideas ? Using Xcode Version 7.3 (7D175)

**Comment by Frugghi** [comment]
Fixed! Thank you :)

**Comment by ChristianVirtual** [comment]
worked & Thank you too for the quick response !
