### ISSUE TITLE
Compiling for Apple Silicon

### ISSUE THREAD

**Issue by Iomegan** [Frugghi/iSSH2#12]
Hi,

`./iSSH2.sh --platform=macosx --archs=arm64 --min-version=10.16   `

gives me a simple

`Build failed, cleaning up temporary files...`

Has anyone been able to modify the script to get a ARM build for macOS?

OpenSSL should build for ARM (https://github.com/openssl/openssl/commit/61168b5b8dde03f3b77ddf5e4b1b81c338c01746) not so sure about libssh2

**Comment by Jan-E** [comment]
Did you try it with --min-version=11.0?

**Comment by Iomegan** [comment]
Yes, same result. Is there a way to get a more detailed error log?

**Comment by Jan-E** [comment]
Remove the >> "$LOG" 2>&1 at the end of iSSH2-libssh2.sh (3 times) and the output will be shown on screen.

**Comment by Jan-E** [comment]
Remove the >> "$LOG" 2>&1 near the end of iSSH2-openssl.sh (3 times) and the output of building OpenSSL will also be shown on screen. Lines 89, 95, 96.

**Comment by Iomegan** [comment]
Thanks. Already fails with OpenSSL. Should be `darwin64-arm64-cc` not `darwin-arm64-cc`

**Comment by Iomegan** [comment]
adding
`      elif [[ "$ARCH" == "arm64" ]]; then
        HOST="darwin64-arm64-cc"
`
did help. 

`./iSSH2.sh --platform=macosx --archs=arm64,x86_64 --min-version=10.16` fails, not sure why. I can probably lipo that manually.

**Comment by Jan-E** [comment]
Remove the cleanupFail $CLEAN_BUILD in iSSH2.sh (a couple of times) to retain the intermediate results.

**Comment by Iomegan** [comment]
It fails at the same line as before, but I am not sure how to change the script to load, compile and merge both platforms. For iOS there is `ios-cross`, but there's nothing like that for macOS. I don't understand that part of the script.

For now I am building both architectures separately and merge them manually:
`lipo -create arm64/libssh2.a x86_64/libssh2.a -output libssh2.a`

**Comment by Jan-E** [comment]
`./iSSH2.sh --platform=macosx --archs="arm64 x86_64" --min-version=10.16`
or
`./iSSH2.sh --platform=macosx --archs="arm64 x86_64" --min-version=11.0`
should probably work

**Comment by Jan-E** [comment]
https://github.com/Jan-E/iSSH2/commit/c0501dd6bcc449f65ea58e57f69fb98c56736a56
```
From c0501dd6bcc449f65ea58e57f69fb98c56736a56 Mon Sep 17 00:00:00 2001
From: Jan-E
Date: Fri, 11 Dec 2020 05:24:09 +0100
Subject: [PATCH] Build arm64 with MacOSX SDK 11.0

---
 iSSH2-openssl.sh | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/iSSH2-openssl.sh b/iSSH2-openssl.sh
index 25fe2d7..9ca78b7 100755
--- a/iSSH2-openssl.sh
+++ b/iSSH2-openssl.sh
@@ -69,6 +69,8 @@ do
     if [[ "$SDK_PLATFORM" == "macosx" ]]; then
       if [[ "$ARCH" == "x86_64" ]]; then
         HOST="darwin64-x86_64-cc"
+      elif [[ "$ARCH" == "arm64" ]] && [[ $SDK_VERSION > 10.15 ]]; then
+        HOST="darwin64-arm64-cc"
       else
         HOST="darwin-$ARCH-cc"
       fi
```
results in
```
% ./iSSH2.sh --platform=macosx --archs="x86_64 arm64" --min-version=10.16
Initializing...

Libssh2 version: 1.9.0 (Automatically detected)
OpenSSL version: 1.1.1i (Automatically detected)
SDK version: 11.0 (Automatically detected)
Xcode version: 12.2 (Automatically detected)
Architectures: arm64 x86_64 
Platform: macosx
Platform min version: 10.16

openssl-1.1.1i.tar.gz already exists
MD5: 08987c3cf125202e2b0840035efb392c
Extracting openssl-1.1.1i.tar.gz
Building OpenSSL 1.1.1i, please wait...
- MacOSX arm64 done!
- MacOSX x86_64 done!
Building libssl.a fat library...
Building libcrypto.a fat library...
Copying headers...
Building done.
Downloading libssh2-1.9.0.tar.gz
############################################################################################################################################### 100.0%############################################################################################################################################### 100.0%
MD5: 1beefafe8963982adc84b408b2959927
Extracting libssh2-1.9.0.tar.gz
Building Libssh2 1.9.0:
- MacOSX arm64 done!
- MacOSX x86_64 done!
Building libssh2.a fat library...
Copying headers...
Building done.
Cleaning up temporary files...

```

**Comment by Jan-E** [comment]
> SDK version: 11.0 (Automatically detected)

Which version are you getting? 11.0 or 10.16?

**Comment by Iomegan** [comment]
Thanks. With your latest version I get `SDK version 11.0`.

**Comment by Jan-E** [comment]
I made a new commit to my fork: https://github.com/Jan-E/iSSH2/commit/7f460bcde3bb2baeec11bee1ab9a9a24fcbd7cd8
This automatically builds arm64 for silicon in Xcode >- 12.
I will make a PR for this in the repo of @Frugghi

**Comment by Jan-E** [comment]
PR: https://github.com/Frugghi/iSSH2/pull/13
