### ISSUE TITLE
build failed for macosx 

### ISSUE THREAD

**Issue by fahadhaq** [Frugghi/iSSH2#18]
When I ran the script I am getting the following error

`Initializing...

Libssh2 version: 1.9.0 (Automatically detected)
OpenSSL version: 1.1.1r (Automatically detected)
SDK version: 16.0 (Automatically detected)
Xcode version: 14.0.1 (Automatically detected)
Architectures: arm64 arm64e armv7 armv7s i386 x86_64 
Platform: iphoneos
Platform min version: 8.0

openssl-1.1.1r.tar.gz already exists
MD5: bb8a5c2eff5c060e1701541ab2a02b88
Extracting openssl-1.1.1r.tar.gz
Building OpenSSL 1.1.1r, please wait...
Build failed, cleaning up temporary files...`

here is the command I am running

`./iSSH2.sh --platform=iphoneos --min-version=8.0`

I am running this on macosx monterey

Any help would be greatly appreciated. Thanks

**Comment by fahadhaq** [comment]
for anyone having similar errors running the following command seems to fix the issue

`./iSSH2.sh --platform=iphoneos --min-version=8.0 --openssl=1.1.1c --libssh2=1.9.0`

**Comment by Jan-E** [comment]
Looks like you are building the libs for an iPhone or iPad app. With Xcode 14 and target iOS 16 the 32-bits architectures (armv7 armv7s i386) are not supported anymore. Try building with something like --archs="arm64 arm64e x86_64". Not tested, but I think this is the required syntax for the --archs argument.

**Comment by Jan-E** [comment]
> OpenSSL version: 1.1.1r (Automatically detected)

OpenSSL 1.1.1r has been retracted by the OpenSSL devs: https://github.com/openssl/general-policies/pull/32 
So you are downloading a stub. --openssl=1.1.1q should work.

And while you are at it: try --libssh2=1.10.0. If that does not build the stable release of libssh2 you will have to patch the script:
https://github.com/Jan-E/iSSH2/commit/a1a1b82527aad16811270d23cc0c20fd3d64f70d

**Comment by Jan-E** [comment]
OpenSSL 1.1.1s will be made available on Tuesday 1st November 2022 between 1300-1700 UTC, according to an announcement by the OpenSSL devs.

**Comment by fahadhaq** [comment]
Thanks @Jan-E for your help. Really appreciate it

**Comment by Jan-E** [comment]
Ok. Please close this issue.

**Comment by Jan-E** [comment]
If it does not detect it yet add —openssl=1.1.1s now.
