### ISSUE TITLE
Does not seem to work on XCode 8

### ISSUE THREAD

**Issue by ezathashim** [Frugghi/iSSH2#2]
Is anyone else having issues on XCode 8?

**Comment by Frugghi** [comment]
I've not tested it with Xcode 8 yet, but I'm happy to accept PR!

**Comment by ezathashim** [comment]
PR?

**Comment by Frugghi** [comment]
Pull request

**Comment by ezathashim** [comment]
I wish I could, but I'm not familiar with this type of code.
