### ISSUE TITLE
macOS 14 (Sonoma) and Xcode 15 support

### ISSUE THREAD

**Issue by Jan-E** [Frugghi/iSSH2#20]
I know this is an early call, but at the moment this script fails on macOS 14 beta (Sonoma) with Xcode 15 beta:
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by williamhqs** [comment]
use Xcode-select to select Xcode or use select the Command Line Tools from Xcode settings should be able to fix this issue. Note if "command line tools" is filled already also select it again.

Not sure helps but try.

<img width="612" alt="Screenshot 2023-12-04 at 17 00 50" src="https://github.com/Frugghi/iSSH2/assets/354829/d1e42603-a565-41ed-9c01-720722247fff">

**Comment by Jan-E** [comment]
In Sonoma 14.1 all was normal again. Sonama 14.2 resulted in a normal build. Closing.
