### ISSUE TITLE
Compile fail on SDK 12.2

### ISSUE THREAD

**Issue by MoonTechiOSDev1** [Frugghi/iSSH2#8]
We have tried to build a script in macOS 10.14.4 and xcode 10.2.1 

`MAC29:iSSH2-master mtp$ ./iSSH2.sh
Initializing...

Libssh2 version: 1.8.2 (Automatically detected)
OpenSSL version: 1.1.1b (Automatically detected)
SDK version: 12.2 (Automatically detected)
Architectures: armv7 armv7s arm64 x86_64
OS min version: 8.0

openssl-1.1.1b.tar.gz already exists
MD5: 4532712e7bcc9414f5bce995e4e13930
Extracting openssl-1.1.1b.tar.gz
Building OpenSSL 1.1.1b, please wait...
libssl.a and libcrypto.a for armv7 already exist.
libssl.a and libcrypto.a for armv7s already exist.
libssl.a and libcrypto.a for arm64 already exist.
libssl.a and libcrypto.a for x86_64 already exist.
Building libssl.a fat library...
Building libcrypto.a fat library...
Copying headers...
Building done.
libssh2-1.8.2.tar.gz already exists
MD5: 616efd99af3d9ef731a26bed6cee9593
Extracting libssh2-1.8.2.tar.gz
Building Libssh2 1.8.2:
Build failed, cleaning up temporary files...
MAC29:iSSH2-master mtp$ `

**Comment by Jan-E** [comment]
For OpenSSL 1.1.1 you will have to patch libssh2 (1.8.2):
https://github.com/Jan-E/iSSH2/commit/6b2b61d56fc43642980aacc529c9d9d14263cebf
or use my fork at https://github.com/Jan-E/iSSH2/tree/fix-openssl-1.1.1

But then it compiles fine with
./iSSH2.sh --openssl=1.1.1b --libssh2=1.8.2

See https://github.com/Frugghi/iSSH2/issues/7#issuecomment-477787612 for the output of the build process.

**Comment by MoonTechiOSDev1** [comment]
Thanks!

Above patch working fine with 12.2.

**Comment by Jan-E** [comment]
libssh2 1.9.0 was released...
